name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build Go application
      run: go build -o portfolio main.go
      
    - name: Generate static HTML
      run: |
        # Create a temporary server to generate static HTML
        ./portfolio &
        SERVER_PID=$!
        
        # Wait for server to start and check if it's running
        for i in {1..10}; do
          if curl -f http://localhost:8080/ > /dev/null 2>&1; then
            echo "Server is running"
            break
          fi
          echo "Waiting for server to start... ($i/10)"
          sleep 2
        done
        
        # Generate static HTML files
        mkdir -p dist
        curl -s http://localhost:8080/ > dist/index.html
        
        # Verify HTML was generated
        if [ ! -s dist/index.html ]; then
          echo "Error: Failed to generate index.html"
          exit 1
        fi
        
        # Copy static assets
        cp -r static dist/
        cp -r public dist/
        cp _headers dist/
        cp _redirects dist/
        cp robots.txt dist/
        cp sitemap.xml dist/
        
        # Kill the server
        kill $SERVER_PID 2>/dev/null || true
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
