name: Deploy Static Site to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Generate static HTML
      run: |
        # Create a temporary server to generate the HTML
        go run main.go &
        SERVER_PID=$!
        sleep 5
        
        # Download the generated HTML
        curl -o index.html http://localhost:8080/
        
        # Kill the server
        kill $SERVER_PID
        
    - name: Create static site structure
      run: |
        mkdir -p dist
        cp index.html dist/
        cp -r static dist/
        cp -r public dist/
        cp robots.txt dist/
        cp sitemap.xml dist/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: arnis.wtf
